const http = require('http');
const BASE = 'http://127.0.0.1:3001';
function req(m,p,d,t){return new Promise((a,e)=>{const u=new URL(BASE+p);const b=d?JSON.stringify(d):null;const o={hostname:u.hostname,port:u.port,path:u.pathname+u.search,method:m,headers:{'Content-Type':'application/json'}};if(t)o.headers.Authorization='Bearer '+t;if(b)o.headers['Content-Length']=Buffer.byteLength(b);const r=http.request(o,res=>{let x='';res.on('data',c=>x+=c);res.on('end',()=>{try{a({status:res.statusCode,data:JSON.parse(x)})}catch{a({status:res.statusCode,data:x})}})});r.on('error',e);if(b)r.write(b);r.end()})}
function tasksOf(r){return r.data?.data?.tasks||r.data?.tasks||[]}
let pass=0,fail=0;
async function t(n,f,s,cmp){try{const r=await f();if(s&&r.status!==s){console.log('  FAIL',n,'exp',s,'got',r.status);fail++;return r}if(cmp&&!cmp(r)){console.log('  FAIL',n,'assert failed');fail++;return r}console.log('  PASS',n);pass++;return r}catch(e){console.log('  FAIL',n,e.message);fail++}}
(async()=>{
const R=Date.now();
console.log('=== 1. register ===');
await t('register',()=>req('POST','/api/v1/auth/register',{username:'V_'+R,password:'Test123456',agreeTerms:true}),200);
console.log('=== 2. login ===');
const lg=await t('login',()=>req('POST','/api/v1/auth/login',{username:'V_'+R,password:'Test123456'}),200);
const tok=lg.data.data.token;const me=lg.data.data.user;
console.log('=== 3. list empty (default origin=team) ===');
await t('list-empty',()=>req('GET','/api/v1/task-team',null,tok),200,r=>tasksOf(r).length===0);
console.log('=== 4. create team task ===');
const c=await t('create-team',()=>req('POST','/api/v1/task-team',{title:'Team Smoke',status:'pending',priority:'high',origin:'team'}),200,r=>r.data.data.id&&r.data.data.origin==='team');
const tid=c.data.data.id;
console.log('=== 5. create personal task ===');
const p=await t('create-personal',()=>req('POST','/api/v1/task-team',{title:'Pers Smoke',status:'pending',priority:'low',origin:'personal'}),200,r=>r.data.data.id&&r.data.data.origin==='personal');
const pid=p.data.data.id;
console.log('=== 6. get team detail ===');
await t('get-detail',()=>req('GET','/api/v1/task-team/'+tid,null,tok),200,r=>r.data.data.id===tid);
console.log('=== 7. list origin=team (expect 1) ===');
await t('list-team',()=>req('GET','/api/v1/task-team?origin=team',null,tok),200,r=>tasksOf(r).length===1);
console.log('=== 8. list origin=personal (expect 1) ===');
await t('list-personal',()=>req('GET','/api/v1/task-team?origin=personal',null,tok),200,r=>tasksOf(r).length===1);
console.log('=== 9. list origin=all (expect 2) ===');
await t('list-all',()=>req('GET','/api/v1/task-team?origin=all',null,tok),200,r=>tasksOf(r).length===2);
console.log('=== 10. list default=team (expect 1, personal filtered) ===');
await t('list-default',()=>req('GET','/api/v1/task-team',null,tok),200,r=>tasksOf(r).length===1);
console.log('=== 11. search ===');
await t('search',()=>req('GET','/api/v1/task-team?origin=all&search=Team',null,tok),200,r=>tasksOf(r).length===1);
console.log('=== 12. PATCH status pending->in_progress ===');
await t('st-prog',()=>req('PATCH','/api/v1/task-team/'+tid+'/status',{status:'in_progress'},tok),200,r=>r.data.data.status==='in_progress');
console.log('=== 13. PATCH status in_progress->completed ===');
await t('st-done',()=>req('PATCH','/api/v1/task-team/'+tid+'/status',{status:'completed'},tok),200,r=>r.data.data.status==='completed');
console.log('=== 14. verify completedAt auto ===');
await t('completedAt-auto',()=>req('GET','/api/v1/task-team/'+tid,null,tok),200,r=>!!r.data.data.completedAt);
console.log('=== 15. PATCH reassign self ===');
await t('reassign',()=>req('PATCH','/api/v1/task-team/'+tid+'/reassign',{assigneeId:me.id},tok),200);
console.log('=== 16. DELETE team ===');
await t('del-team',()=>req('DELETE','/api/v1/task-team/'+tid,null,tok),200);
console.log('=== 17. DELETE personal ===');
await t('del-personal',()=>req('DELETE','/api/v1/task-team/'+pid,null,tok),200);
console.log('=== 18. final cleared ===');
await t('final-clear',()=>req('GET','/api/v1/task-team?origin=all',null,tok),200,r=>tasksOf(r).length===0);
console.log('');
console.log('========== RESULT: '+pass+' PASS / '+fail+' FAIL ==========');
process.exit(fail>0?1:0);
})();